export const libraryEntries = [
  {
    id: "seven-archangels",
    title: "Book of the Seven Archangels",
    original: "7大天使召唤之书",
    category: "Spells & Rituals",
    tradition: "Western Ceremonial Magic",
    kind: "Grimoire / Invocation",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "spells",
    sourceFile: "7大天使召唤之书.pdf",
    summary: "A Chinese-language source indexed in the uploaded collection. Full article content remains locked until the original source is extracted and reviewed."
  },
  {
    id: "domesius-21-spells",
    title: "Domesius — 21 Spells",
    original: "Domesius21条咒语 中文版",
    category: "Spells & Rituals",
    tradition: "Western Magic",
    kind: "Spell Collection",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "spells",
    sourceFile: "Domesius21条咒语 中文版.pdf",
    summary: "A Chinese spell collection is present in the archive. The prototype indexes the work without inventing untranslated instructions."
  },
  {
    id: "turiel",
    title: "The Secret Magic of Turiel",
    original: "Turiel;的奥秘魔法之书",
    category: "Grimoires",
    tradition: "Western Esotericism",
    kind: "Grimoire",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "grimoires",
    sourceFile: "Turiel;的奥秘魔法之书.doc",
    summary: "A Turiel-related magical text appears in the uploaded library inventory and is reserved for later source extraction."
  },
  {
    id: "enochian-documents",
    title: "Enochian Magical Documents",
    original: "《以诺魔法文献》",
    category: "Spells & Rituals",
    tradition: "Enochian / Ceremonial Magic",
    kind: "Source Collection",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "rituals",
    sourceFile: "《以诺魔法文献》.pdf",
    summary: "A Chinese-language Enochian magic source is present. The encyclopedia record is prepared for bilingual annotation after extraction."
  },
  {
    id: "dictionnaire-infernal",
    title: "Dictionnaire Infernal",
    original: "《地狱辞典》",
    category: "Entities",
    tradition: "European Demonology",
    kind: "Reference",
    language: "Chinese + English detected",
    status: "Bilingual sources detected",
    visual: "entities",
    sourceFile: "《地狱辞典》中文版.pdf",
    summary: "Chinese and English versions are both represented in the inventory, making this a strong candidate for future bilingual comparison."
  },
  {
    id: "mystical-qabalah",
    title: "The Mystical Qabalah",
    original: "《密契卡巴拉》 by Dion Fortune",
    category: "Traditions",
    tradition: "Qabalah",
    kind: "Study / Reference",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "traditions",
    sourceFile: "《密契卡巴拉》+by+Dion+Fortune.pdf",
    summary: "A Chinese edition of Dion Fortune's Qabalah-related work is indexed in the collection."
  },
  {
    id: "golden-dawn-scrolls",
    title: "Scrolls of the Golden Dawn",
    original: "《金色黎明的卷轴》",
    category: "Traditions",
    tradition: "Golden Dawn",
    kind: "Source Text",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "traditions",
    sourceFile: "《金色黎明的卷轴》.pdf",
    summary: "A Golden Dawn source is present alongside several other Golden Dawn and Qabalah-related files."
  },
  {
    id: "medieval-alchemy",
    title: "Alchemy in Medieval Europe",
    original: "中世纪欧洲的炼金术",
    category: "Alchemy",
    tradition: "Western Alchemy",
    kind: "Historical Study",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "alchemy",
    sourceFile: "中世纪欧洲的炼金术.doc",
    summary: "A Chinese-language historical source on medieval European alchemy is present in the archive."
  },
  {
    id: "miao-witchcraft",
    title: "Perspectives on Miao Witchcraft in China",
    original: "中国苗族巫术透视",
    category: "Historical Magic",
    tradition: "Chinese Ethnographic / Folk Study",
    kind: "Study",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "historical",
    sourceFile: "中国苗族巫术透视.pdf",
    summary: "A Chinese study focusing on Miao witchcraft is indexed in the source collection."
  },
  {
    id: "southwest-minority-religion",
    title: "Religion and Witchcraft among Ethnic Minorities of Southwest China",
    original: "中国西南少数民族的宗教与巫术",
    category: "Historical Magic",
    tradition: "Chinese Ethnographic / Folk Study",
    kind: "Study",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "historical",
    sourceFile: "中国西南少数民族的宗教与巫术.pdf",
    summary: "A source on religion and witchcraft among ethnic minorities of Southwest China is present in the archive."
  },
  {
    id: "heptameron",
    title: "Heptameron",
    original: "中文翻译：魔法大全《Heptameron》",
    category: "Grimoires",
    tradition: "Western Ceremonial Magic",
    kind: "Grimoire",
    language: "Chinese + English detected",
    status: "Bilingual sources detected",
    visual: "grimoires",
    sourceFile: "中文翻译：魔法大全《Heptameron音译：哈茨麦雯德》.doc",
    summary: "The archive contains Chinese Heptameron material and English-associated versions, making it suitable for later cross-checked translation."
  },
  {
    id: "hexagram-ritual",
    title: "Hexagram Ritual",
    original: "六芒星仪式",
    category: "Spells & Rituals",
    tradition: "Western Ceremonial Magic",
    kind: "Ritual Text",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "rituals",
    sourceFile: "六芒星仪式.pdf",
    summary: "A dedicated source titled Hexagram Ritual is indexed. Detailed ritual content remains source-locked."
  },
  {
    id: "pentagram-drawing",
    title: "On Drawing the Pentagram",
    original: "关于五芒星的画法",
    category: "Artifacts & Symbols",
    tradition: "Western Symbolism",
    kind: "Symbol Reference",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "artifacts",
    sourceFile: "关于五芒星的画法.doc",
    summary: "A source devoted to pentagram drawing appears in the archive and is reserved for later visual annotation."
  },
  {
    id: "kabbalah-foundations",
    title: "Kabbalah — Foundations of the Western Magical Tradition",
    original: "卡巴拉 - 犹太的智慧, 西方魔法传统的基础",
    category: "Traditions",
    tradition: "Kabbalah",
    kind: "Study / Reference",
    language: "Chinese",
    status: "Multiple sources detected",
    visual: "traditions",
    sourceFile: "卡巴拉 - 犹太的智慧, 西方魔法传统的基础.doc",
    summary: "The collection contains several Kabbalah-focused documents, including introductory and Golden Dawn-related material."
  },
  {
    id: "runes",
    title: "Runes and Runic Symbols",
    original: "卢嗯符号（如尼符文）",
    category: "Artifacts & Symbols",
    tradition: "Northern European",
    kind: "Symbol Reference",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "artifacts",
    sourceFile: "卢嗯符号（如尼符文）.pdf",
    summary: "A dedicated runic-symbol source is present and is a priority for the future interactive symbol viewer."
  },
  {
    id: "ancient-egyptian-spells",
    title: "Ancient Egyptian Spells",
    original: "古埃及的咒语（全）",
    category: "Spells & Rituals",
    tradition: "Ancient Egyptian",
    kind: "Spell Collection",
    language: "Chinese",
    status: "Large scanned PDF detected",
    visual: "spells",
    sourceFile: "古埃及的咒语（全）.pdf",
    summary: "A large scanned source devoted to Ancient Egyptian spells is present and will later support manuscript imagery and article extraction."
  },
  {
    id: "book-of-the-dead",
    title: "Egyptian Book of the Dead",
    original: "埃及亡灵书",
    category: "Historical Magic",
    tradition: "Ancient Egyptian",
    kind: "Historical / Religious Text",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "historical",
    sourceFile: "埃及亡灵书.pdf",
    summary: "A Chinese-language source for the Egyptian Book of the Dead is indexed and will be handled as historical and religious source material."
  },
  {
    id: "amulet-making",
    title: "Amulet Making",
    original: "护身符制作",
    category: "Artifacts & Symbols",
    tradition: "Unclassified in inventory",
    kind: "Artifact / Practice",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "artifacts",
    sourceFile: "护身符制作.doc",
    summary: "A dedicated source on amulet making is present. Practical details remain source-locked until the original file is reviewed."
  },
  {
    id: "dunhuang-witchcraft",
    title: "Dunhuang Witchcraft and Its Historical Development",
    original: "敦煌巫术与巫术流变",
    category: "Historical Magic",
    tradition: "Chinese Historical Study",
    kind: "Study",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "historical",
    sourceFile: "敦煌巫术与巫术流变.pdf",
    summary: "A Chinese historical source on Dunhuang witchcraft and its development appears in the library."
  },
  {
    id: "european-symbols",
    title: "European Symbol Collection — Astrology and Astronomy",
    original: "欧洲符号集（占星及天文）",
    category: "Artifacts & Symbols",
    tradition: "European Astrology / Astronomy",
    kind: "Illustrated Symbol Reference",
    language: "Chinese",
    status: "Visual source detected",
    visual: "artifacts",
    sourceFile: "欧洲符号集%28占星及天文%29.docx",
    summary: "A European symbol collection focused on astrology and astronomy is present and is promising for diagram extraction."
  },
  {
    id: "flower-shadow-tarot",
    title: "Flower Shadow Tarot — Full-Color Chinese Guide",
    original: "花影塔罗说明书中译全彩电子版",
    category: "Divination",
    tradition: "Tarot",
    kind: "Illustrated Guide",
    language: "Chinese",
    status: "Full-color PDF detected",
    visual: "divination",
    sourceFile: "花影塔罗说明书中译全彩电子版.pdf",
    summary: "A full-color translated tarot guide is present and is a priority visual source for the future divination gallery."
  },
  {
    id: "arbatel",
    title: "Arbatel of Magic",
    original: "《阿巴太尔》（Arbatel Of Magic）",
    category: "Grimoires",
    tradition: "Western Esotericism",
    kind: "Grimoire",
    language: "English source folder",
    status: "English source detected",
    visual: "grimoires",
    sourceFile: "英文版本魔法资料/《阿巴太尔》（Arbatel Of Magic ）.pdf",
    summary: "An English Arbatel source is present in the dedicated English-material folder."
  },
  {
    id: "grand-grimoire",
    title: "Grand Grimoire",
    original: "《大魔法书》（Grand Grimoire）",
    category: "Grimoires",
    tradition: "European Grimoire Tradition",
    kind: "Grimoire",
    language: "English source folder",
    status: "English source detected",
    visual: "grimoires",
    sourceFile: "英文版本魔法资料/《大魔法书》（Grand Grimoire）.pdf",
    summary: "An English Grand Grimoire source appears in the archive's English-material folder."
  },
  {
    id: "lesser-key",
    title: "The Lesser Key of Solomon",
    original: "《所罗门的小钥匙》（Lemegeton）",
    category: "Grimoires",
    tradition: "Solomonic Magic",
    kind: "Grimoire",
    language: "English source folder",
    status: "English source detected",
    visual: "grimoires",
    sourceFile: "英文版本魔法资料/《所罗门的小钥匙》（Lemegeton）.pdf",
    summary: "An English Lesser Key of Solomon source is present and can later become a hub for linked source entities, symbols, tools, and ritual structures."
  },
  {
    id: "plant-power",
    title: "The Power of Plants — Potions and Magical Herbs",
    original: "《植物的力量：药剂与魔草》",
    category: "Plants & Materials",
    tradition: "Herbal / Magical Plant Lore",
    kind: "Reference",
    language: "English source folder",
    status: "English source detected",
    visual: "plants",
    sourceFile: "英文版本魔法资料/《植物的力量：药剂与魔草》.pdf",
    summary: "A plant, potion, and magical-herb source is present in the English-material folder."
  },
  {
    id: "rune-magic",
    title: "Rune Magic",
    original: "《符文魔法》",
    category: "Artifacts & Symbols",
    tradition: "Runic / Northern European",
    kind: "Reference",
    language: "English source folder",
    status: "English source detected",
    visual: "artifacts",
    sourceFile: "英文版本魔法资料/《符文魔法》.pdf",
    summary: "An English-folder source on rune magic is indexed and can later complement the Chinese runic-symbol reference."
  },
  {
    id: "book-of-raziel",
    title: "The Book of Raziel",
    original: "《罗洁爱尔之书》(The Book of Raziel)",
    category: "Grimoires",
    tradition: "Jewish / Western Esoteric Tradition",
    kind: "Grimoire",
    language: "English source folder",
    status: "PDF + text sources detected",
    visual: "grimoires",
    sourceFile: "英文版本魔法资料/《罗洁爱尔之书》(The_Book_of_Raziel).pdf",
    summary: "Multiple Raziel-related sources are present, including PDF and text material suitable for future source comparison."
  },
  {
    id: "golden-dawn-compendium",
    title: "Golden Dawn Magic Compendium",
    original: "《金光黎明会魔法大全》",
    category: "Traditions",
    tradition: "Golden Dawn",
    kind: "Compendium",
    language: "English source folder",
    status: "English source detected",
    visual: "traditions",
    sourceFile: "英文版本魔法资料/《金光黎明会魔法大全》.pdf",
    summary: "A substantial Golden Dawn magic compendium is indexed in the English-material folder."
  },
  {
    id: "angel-demon-symbols",
    title: "Symbols of Angels and Demons",
    original: "恶魔天使的符号",
    category: "Artifacts & Symbols",
    tradition: "Western Esotericism",
    kind: "Symbol Reference",
    language: "English source folder",
    status: "Visual source detected",
    visual: "entities",
    sourceFile: "英文版本魔法资料/恶魔天使的符号.pdf",
    summary: "A symbol-focused source on angels and demons is present and is a priority candidate for the future interactive image viewer."
  },
  {
    id: "christian-astrology",
    title: "Christian Astrology — Book I",
    original: "威廉·莉莉_基督占星（第一册）_中文译本",
    category: "Divination",
    tradition: "Western Astrology",
    kind: "Astrology Text",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "divination",
    sourceFile: "威廉·莉莉_基督占星（第一册）_中文译本.doc",
    summary: "A Chinese translation of William Lilly's astrology material is present alongside additional astrology texts."
  },
  {
    id: "alchemy-great-mystery",
    title: "Alchemy — The Great Mystery",
    original: "炼金术-伟大的奥秘",
    category: "Alchemy",
    tradition: "Western Alchemy",
    kind: "Study / Reference",
    language: "Chinese",
    status: "Inventory indexed",
    visual: "alchemy",
    sourceFile: "炼金术-伟大的奥秘.pdf",
    summary: "One of several alchemy-related works in the collection, alongside medieval and spiritual alchemy material."
  },
  {
    id: "magic-circles",
    title: "Magic Circles",
    original: "魔法阵",
    category: "Artifacts & Symbols",
    tradition: "Multiple / Unclassified",
    kind: "Diagram Collection",
    language: "Chinese",
    status: "DOC + large RAR detected",
    visual: "artifacts",
    sourceFile: "魔法阵.rar",
    summary: "A dedicated magic-circle document and a large RAR asset archive were detected. This is a priority visual source for the interactive diagram viewer."
  },
  {
    id: "magical-botany",
    title: "Magical Botany",
    original: "《魔法植物学》",
    category: "Plants & Materials",
    tradition: "Magical Plant Lore",
    kind: "Reference",
    language: "English source folder",
    status: "English source detected",
    visual: "plants",
    sourceFile: "英文版本魔法资料/《魔法植物学》.pdf",
    summary: "A magical botany source is present alongside additional plant and potion material."
  }
];

export const categories = [
  "All",
  "Spells & Rituals",
  "Grimoires",
  "Artifacts & Symbols",
  "Traditions",
  "Entities",
  "Divination",
  "Alchemy",
  "Plants & Materials",
  "Historical Magic"
];

export const learningChapters = [
  {
    number: "I",
    title: "Foundations",
    subtitle: "Learn how the archive speaks",
    description: "Terminology, source reading, magical worldviews, correspondences, historical context, and the difference between tradition, later interpretation, and modern reconstruction.",
    topics: ["Terminology", "Source literacy", "Symbols", "Historical context"]
  },
  {
    number: "II",
    title: "Spellcraft",
    subtitle: "Read spells as structured systems",
    description: "Study indexed spell collections by origin, source, stated purpose, associated symbols, and relationships to larger traditions.",
    topics: ["Spell collections", "Incantation forms", "Correspondences", "Source comparison"]
  },
  {
    number: "III",
    title: "Ritual Architecture",
    subtitle: "Understand the shape of ceremony",
    description: "Explore how source texts describe ritual space, sequencing, tools, symbols, and ceremonial frameworks without separating them from their historical context.",
    topics: ["Sacred space", "Sequence", "Tools", "Ceremonial systems"]
  },
  {
    number: "IV",
    title: "Artifacts & Symbols",
    subtitle: "Read the visual language",
    description: "Examine talismans, circles, runes, sigils, diagrams, manuscripts, and symbolic objects through source-linked visual records.",
    topics: ["Talismans", "Magic circles", "Runes", "Sigils"]
  },
  {
    number: "V",
    title: "Traditions",
    subtitle: "Compare without flattening",
    description: "Navigate distinct historical and cultural traditions while retaining original terminology, provenance, and source boundaries.",
    topics: ["Chinese historical studies", "Golden Dawn", "Kabbalah", "Egyptian sources"]
  }
];

export const archiveStats = {
  splitVolumes: 20,
  rawFiles: 256,
  rawFolders: 1,
  totalArchiveBytes: 1861581400,
  note: "The inventory contains obvious duplicate filename pairs. Deduplication is planned before full-text import."
};
